apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
  namespace: default
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: milestone2-selfsigned
  namespace: default
spec:
  secretName: milestone2-tls
  duration: 2160h # 90d
  renewBefore: 720h # 30d
  commonName: localhost
  isCA: false
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
  dnsNames:
  - localhost
